//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadeSaude
    {
        public int Id { get; set; }
        public string Tipo_Instituição { get; set; }
        public string Tipo_Emergência { get; set; }
        public string Nome { get; set; }
        public string Endereço { get; set; }
        public string Telefone { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string Link_pt { get; set; }
        public string Link_en { get; set; }
        public string Link_es { get; set; }
        public string Especialidades_pt { get; set; }
        public string Especialidades_en { get; set; }
        public string Especialidades_es { get; set; }
    }
}
